# Generated by Django 4.1.5 on 2023-02-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOdonto', '0002_delete_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePaciente', models.CharField(max_length=15)),
                ('servicio', models.CharField(max_length=15)),
                ('fecha', models.DateField()),
                ('horario', models.TimeField()),
            ],
        ),
    ]
