# Generated by Django 4.1.5 on 2023-02-28 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppOdonto', '0003_turno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turno',
            old_name='nombrePaciente',
            new_name='paciente',
        ),
    ]
