# Generated by Django 4.1.5 on 2023-02-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOdonto', '0004_rename_nombrepaciente_turno_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=15)),
                ('servicio', models.CharField(max_length=15)),
                ('profesional', models.CharField(max_length=15)),
                ('fecha', models.DateField()),
                ('horario', models.TimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Paciente',
            new_name='PacienteModel',
        ),
        migrations.RenameModel(
            old_name='Profesional',
            new_name='ProfesionalModel',
        ),
        migrations.RenameModel(
            old_name='Servicio',
            new_name='ServicioModel',
        ),
        migrations.DeleteModel(
            name='Turno',
        ),
    ]
