# Generated by Django 4.1.5 on 2023-02-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppOdonto', '0005_turnomodel_rename_paciente_pacientemodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PacienteModel',
            new_name='Paciente',
        ),
        migrations.RenameModel(
            old_name='ProfesionalModel',
            new_name='Profesional',
        ),
        migrations.RenameModel(
            old_name='ServicioModel',
            new_name='Servicio',
        ),
        migrations.RenameModel(
            old_name='TurnoModel',
            new_name='Turno',
        ),
    ]
