# Generated by Django 4.1.5 on 2023-03-02 01:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppOdonto', '0007_rename_usuario_avatarimagen_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvatarImagen',
            new_name='Avatar',
        ),
    ]
