# Generated by Django 4.1.5 on 2023-03-02 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppOdonto', '0008_rename_avatarimagen_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='user',
            new_name='usuario',
        ),
    ]
